package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/percona/mongodb_exporter/collector/serverstatusv5"
)

func main() {
	contractPath := flag.String("contract", "collector/serverstatusv5/contract.json", "coverage contract")
	outputPath := flag.String("output", "collector/serverstatusv5/definitions_generated.go", "generated Go output")
	check := flag.Bool("check", false, "fail when output differs")
	flag.Parse()

	data, err := ioutil.ReadFile(*contractPath)
	fatalIf(err)
	contract, err := serverstatusv5.ParseContract(data)
	fatalIf(err)
	fatalIf(contract.ValidatePolicy())
	generated, err := generate(contract)
	fatalIf(err)
	if *check {
		current, err := ioutil.ReadFile(*outputPath)
		fatalIf(err)
		if !bytes.Equal(current, generated) {
			fatalIf(fmt.Errorf("%s is stale; run go run ./cmd/serverstatus-definitions", *outputPath))
		}
		return
	}
	fatalIf(ioutil.WriteFile(*outputPath, generated, 0644))
}

func generate(contract *serverstatusv5.Contract) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/serverstatus-definitions; DO NOT EDIT.\n\npackage serverstatusv5\n\n")
	out.WriteString("var metricDefinitions = []metricDefinition{\n")
	for _, entry := range contract.Entries {
		if entry.Metric != nil {
			writeDefinition(&out, entry, *entry.Metric)
		}
		for _, metric := range entry.AdditionalMetrics {
			writeDefinition(&out, entry, metric)
		}
	}
	out.WriteString("}\n\n")

	roots := []struct {
		name     string
		segments []string
	}{
		{"commands", []string{"metrics", "commands"}},
		{"aggregation_stages", []string{"metrics", "aggStageCounters"}},
		{"operators", []string{"metrics", "operatorCounters"}},
	}
	out.WriteString("var generatedDynamicFamilies = []dynamicFamily{\n")
	for _, root := range roots {
		allowed := make([]string, 0)
		for _, entry := range contract.Entries {
			if hasPrefix(entry.PathSegments, root.segments) {
				allowed = append(allowed, strings.Join(entry.PathSegments[len(root.segments):], "\x00"))
			}
		}
		sort.Strings(allowed)
		fmt.Fprintf(&out, "{Name:%s, Root:%s, Allowed:map[string]struct{}{", strconv.Quote(root.name), stringSlice(root.segments))
		for _, value := range allowed {
			fmt.Fprintf(&out, "%s:{},", strconv.Quote(value))
		}
		out.WriteString("}},\n")
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func writeDefinition(out *bytes.Buffer, entry serverstatusv5.ContractEntry, metric serverstatusv5.MetricContract) {
	fmt.Fprintf(out, "{SourcePath:%s, PathSegments:%s, Family:%s, Help:%s, Type:%s, Conversion:%s, FixedLabels:%s, ValueLabel:%s, AllowedValues:%s, Transform:%s},\n",
		strconv.Quote(entry.Path), stringSlice(entry.PathSegments), strconv.Quote(metric.Family), strconv.Quote(metric.Help), strconv.Quote(metric.Type),
		strconv.FormatFloat(metric.Conversion, 'g', -1, 64), stringMap(metric.Labels), strconv.Quote(metric.ValueLabel), stringSlice(metric.AllowedValues), strconv.Quote(metric.Transform))
}

func hasPrefix(path, prefix []string) bool {
	if len(path) < len(prefix) {
		return false
	}
	for i := range prefix {
		if path[i] != prefix[i] {
			return false
		}
	}
	return true
}
func stringSlice(values []string) string {
	var out strings.Builder
	out.WriteString("[]string{")
	for _, value := range values {
		out.WriteString(strconv.Quote(value))
		out.WriteByte(',')
	}
	out.WriteByte('}')
	return out.String()
}
func stringMap(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("map[string]string{")
	for _, key := range keys {
		out.WriteString(strconv.Quote(key))
		out.WriteByte(':')
		out.WriteString(strconv.Quote(values[key]))
		out.WriteByte(',')
	}
	out.WriteByte('}')
	return out.String()
}
func fatalIf(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
